networks:
  default: development
  development:
    cmd: ganache-cli
    host: http://127.0.0.1
    timeout: 120
    cmd_settings:
      port: 8545
      gas_limit: 120000000
      accounts: 10
      default_balance: 3000000
      evm_version: istanbul
      mnemonic: brownie
      fork: mainnet

dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.3.2
  - GNSPS/solidity-bytes-utils@0.8.0

# path remapping to support OpenZepplin imports with NPM-style path
compiler:
  solc:
    version: 0.8.8
